### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by bittner** [mrpelotazo/snake#2]
This repository has no expressed license. Hence, the source code is governed by strict copyright (i.e. it is forbidden to copy, use, modify and distribute the program in any form).

If you want to provide the entire source code as free software I would suggest you add a [GNU General Public License v3](https://www.gnu.org/licenses/gpl-3.0.en.html) license file.

More information about software licenses: https://help.github.com/articles/licensing-a-repository/

**Comment by mrpelotazo** [comment]
GPLv3 license file added.

**Comment by bittner** [comment]
Awesome, thank you! :1st_place_medal:
